In [1]:
import math, numpy
#Part 1 input data: Air temp (degC), ID (W/sqm), load resistance (ohms)
# - split into training set and a randomly slected small validation set
xdata = [[-10.0, 350, 4.464],
  [-10.0, 650, 4.464],
  [-10.0, 950, 4.464],
  [-10.0, 1250, 4.464],
  [10.0, 350, 4.464],
  [10.0, 650, 4.464],
  [10.0, 950, 4.464],
  [10.0, 1250, 4.464],
  [30.0, 350, 4.464],
  [30.0, 650, 4.464],
  [30.0, 950, 4.464],
  [30.0, 1250, 4.464],
  [-10.0, 350, 6.696],
  [-10.0, 650, 6.696],
  [-10.0, 950, 6.696],
  [-10.0, 1250, 6.696],
  [10.0, 350, 6.696],
  [10.0, 650, 6.696],
  [10.0, 950, 6.696],
  [10.0, 1250, 6.696],
  [30.0, 350, 6.696],
  [30.0, 650, 6.696],
  [30.0, 950, 6.696],
  [30.0, 1250, 6.696],
  [-10.0, 350, 8.928],
  [-10.0, 650, 8.928],
  [-10.0, 950, 8.928],
  [-10.0, 1250, 8.928],
  [10.0, 350, 8.928],
  [10.0, 650, 8.928],
  [10.0, 950, 8.928],
  [10.0, 1250, 8.928],
  [30.0, 350, 8.928],
  [30.0, 650, 8.928],
  [30.0, 950, 8.928],
  [30.0, 1250, 8.928]]


#Part 1 output data: VL (V) and Power out (W)
ydata = [[18.9, 80.3],
 [23.5, 124.6],
 [24.8, 138.6],
 [25.6, 146.9],
 [19.2, 83.1],
 [25.0, 140.5],
 [26.5, 157.6],
 [27.3, 167.5],
 [19.4, 84.7],
 [26.4, 156.7],
 [28.1, 177.7],
 [29.0, 189.4],
 [22.4, 75.2],
 [24.8, 92.2],
 [25.8, 99.7],
 [26.4, 104.6],
 [23.6, 83.7],
 [26.5, 104.9],
 [27.6, 113.8],
 [28.3, 119.6],
 [24.8, 92.0],
 [28.1, 118.2],
 [29.3, 128.8],
 [30.1, 135.5],
 [23.5, 62.2],
 [25.4, 72.5],
 [26.3, 77.6],
 [26.9, 81.1],
 [25.0, 70.3],
 [27.1, 82.7],
 [28.1, 88.7],
 [28.7, 92.8],
 [26.5, 78.6],
 [28.8, 93.5],
 [29.9, 100.5],
 [30.6, 105.2]]


xarray= numpy.array(xdata)
yarray= numpy.array(ydata)
print (xdata)
print (xarray)
print (ydata)
print (yarray)

# Calculate the median for each column
median_values_x = numpy.median(numpy.array(xdata), axis=0)
median_values_y = numpy.median(numpy.array(ydata), axis=0)

print("Median values for each column:", median_values_x, median_values_y)

xdata = (xdata/median_values_x).tolist()
ydata = (ydata/median_values_y).tolist()

print("Normalized xdata: \n", xdata)
print("\n")
print("Normalized ydata: \n",ydata)

[[-10.0, 350, 4.464], [-10.0, 650, 4.464], [-10.0, 950, 4.464], [-10.0, 1250, 4.464], [10.0, 350, 4.464], [10.0, 650, 4.464], [10.0, 950, 4.464], [10.0, 1250, 4.464], [30.0, 350, 4.464], [30.0, 650, 4.464], [30.0, 950, 4.464], [30.0, 1250, 4.464], [-10.0, 350, 6.696], [-10.0, 650, 6.696], [-10.0, 950, 6.696], [-10.0, 1250, 6.696], [10.0, 350, 6.696], [10.0, 650, 6.696], [10.0, 950, 6.696], [10.0, 1250, 6.696], [30.0, 350, 6.696], [30.0, 650, 6.696], [30.0, 950, 6.696], [30.0, 1250, 6.696], [-10.0, 350, 8.928], [-10.0, 650, 8.928], [-10.0, 950, 8.928], [-10.0, 1250, 8.928], [10.0, 350, 8.928], [10.0, 650, 8.928], [10.0, 950, 8.928], [10.0, 1250, 8.928], [30.0, 350, 8.928], [30.0, 650, 8.928], [30.0, 950, 8.928], [30.0, 1250, 8.928]]
[[ -10.     350.       4.464]
 [ -10.     650.       4.464]
 [ -10.     950.       4.464]
 [ -10.    1250.       4.464]
 [  10.     350.       4.464]
 [  10.     650.       4.464]
 [  10.     950.       4.464]
 [  10.    1250.       4.464]
 [  30.     350.  